<a href="https://colab.research.google.com/github/jingkefei/Jingke-Fei_INFO3020_Spring2020/blob/master/finalexam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [1]:
a=input("please input a string:")
print(a)

please input a string:hello world
hello world


Q2

In [0]:
sum=0
for i in range(1001):
    if i%2==0:
      sum=sum+i
print(sum)

250500


Q3

In [0]:
def recursive_product(number_list):
    total=1
    for element in number_list:
        if type(element) is list:
            total*=recursive_sum(element)
        else:
            total*=element
    return total


numbers=[12,10,3,2,[6,[7,8,9],19,21],21]
print(recursive_product(numbers))

18243429120


Q4

In [9]:
import numpy as np
numlist=[[23,43,12],[32,12,52],[15,35,52],[19,28,56]]
arraylist=np.array(numlist)
arraylist[arraylist>20]=0
print(arraylist)
with open("test.txt","w") as myfile:
  myfile.write(str(arraylist))
  

[[ 0  0 12]
 [ 0 12  0]
 [15  0  0]
 [19  0  0]]


Q5

In [20]:
numbers=[1,3,2,4,2,3,2,2,3,2,2,4,2,32,3,2,4,2,3,5,3,2,4,2,2,4,2,2,4,2,2,3,1,3,2,3]
a=numbers.count(1)
b=numbers.count(2)
c=numbers.count(3)
d=numbers.count(4)
e=numbers.count(5)
f=numbers.count(32)

number_count={}
number_count["1"]=a
number_count["2"]=b
number_count["3"]=c
number_count["4"]=d
number_count["5"]=e
number_count["32"]=f
print(number_count)


{'1': 2, '2': 17, '3': 9, '4': 6, '5': 1, '32': 1}


Q6

In [21]:
import copy

class Point:
  def __init__(self,x=0,y=0):
    self.x=x
    self.y=y

  def __str__(self):
    return "({0},{1})".format(self.x,self.y)

def print_point(pt):
  print("({0},{1})".format(pt.x,pt.y))

def newpoint(p1,p2):
  mx=(p1.x+p2.x)
  my=(p1.y+p2.y)
  return Point(mx,my)

p1=Point(1,3)
p2=Point(3,4)
print(newpoint(p1,p2))


(4,7)


Q7

In [63]:
import pandas as pd

filename="catering_sale_all.xls"
data=pd.read_excel(filename,sheet_name='Sheet1')

a=df["chicken feet"].sum()
b=df["steamed dumplings"].sum()
c=df["ribs"].sum()
d=df["full chicken"].sum()
e=df["stuffed bun"].sum()
f=df["flowering cabbage"].sum()
f=df["doufu"].sum()
h=df["chive dumplings"].sum()
i=df["pudding"].sum()
j=df["original cabbage"].sum()

menu=("0 exit \n1 chicken feet\n2 steamed dumplings\n3 ribs\n4 full chicken\n5 stuffed bun\n6 flowering cabbage\n7 doufu\n8 chive dumplings\n9 pudding\n10 original cabbage")
print(menu)
number=int(input("please input a number in the list:"))

if number==1:
  print('the total sale is:',a,'\n',menu)
elif number==2:
  print('the total sale is:',b,'\n',menu)
elif number==3:
  print('the total sale is:',c,'\n',menu)
elif number==4:
  print('the total sale is:',d,'\n',menu)
elif number==5:
  print('the total sale is:',e,'\n',menu)
elif number==6:
  print('the total sale is:',f,'\n',menu)
elif number==7:
  print('the total sale is:',g,'\n',menu)
elif number==8:
  print('the total sale is:',h,'\n',menu)
elif number==9:
  print('the total sale is:',i,'\n',menu)
elif number==10:
  print('the total sale is:',j,'\n',menu)
elif number==0:
  print("Process finished with exit code 255")


0 exit 
1 chicken feet
2 steamed dumplings
3 ribs
4 full chicken
5 stuffed bun
6 flowering cabbage
7 doufu
8 chive dumplings
9 pudding
10 original cabbage
please input a number in the list:1
the total sale is: 10 

 0 exit 
1 chicken feet
2 steamed dumplings
3 ribs
4 full chicken
5 stuffed bun
6 flowering cabbage
7 doufu
8 chive dumplings
9 pudding
10 original cabbage


In [0]:
import matplotlib.pyplot as plt
x=[1,2,3,2,3,2,2,1]
plt.show()

In [0]:
North America
Asia
Africa
Europe
South America
Oceania
Antarctica

Q8

In [0]:
import pymysql

pydb=pymysql.connect('localhost','root','19930625','world')
dbcursor=pydb.cursor()

sql="select lifeexpectancy,continent from country where continent=North America"
command=dbcursor.execute(sql,value)
results=dbcursor.fetchall()

for row in results:
    countrylist.append(row[0])
    lifelist.append(str(row[1]))


print("avglife \t  | \t continent")
for row in data:
  print(str(row[0])+"|\t"+row[1]+"\t")

dbcursor.close()
db.close()
results=""


Q9

In [0]:
import pymysql
import matplotlib.pyplot as plt
from pylab import *

pydb=pymysql.connect('localhost','root','19930625','world')
dbcursor=pydb.cursor()

sql="select population from country where continent=North America"

command=dbcursor.execute(sql,value)
data=dbcursor.fetchall()
NorthAmerica=0
for row in data：
  for i in row:
    NorthAmerica=North America+row[i]

import pymysql
import matplotlib.pyplot as plt
from pylab import *

pydb=pymysql.connect('localhost','root','19930625','world')
dbcursor=pydb.cursor()

sql="select population from country where continent=Asia"

command=dbcursor.execute(sql,value)
data=dbcursor.fetchall()
Asia=0
for row in data：
  for i in row:
    Asia=Asia+row[i]

import pymysql
import matplotlib.pyplot as plt
from pylab import *

pydb=pymysql.connect('localhost','root','19930625','world')
dbcursor=pydb.cursor()

sql="select population from country where continent=North America"

command=dbcursor.execute(sql,value)
data=dbcursor.fetchall()
Africa=0
for row in data：
  for i in row:
    Africa=Africa+row[i]

import pymysql
import matplotlib.pyplot as plt
from pylab import *

pydb=pymysql.connect('localhost','root','19930625','world')
dbcursor=pydb.cursor()

sql="select population from country where continent=North America"

command=dbcursor.execute(sql,value)
data=dbcursor.fetchall()
Europe=0
for row in data：
  for i in row:
    Europe=Europe+row[i]

import pymysql
import matplotlib.pyplot as plt
from pylab import *

pydb=pymysql.connect('localhost','root','19930625','world')
dbcursor=pydb.cursor()

sql="select population from country where continent=North America"

command=dbcursor.execute(sql,value)
data=dbcursor.fetchall()
SouthAmerica=0
for row in data：
  for i in row:
    SouthAmericaSouthAmerica+row[i]

import pymysql
import matplotlib.pyplot as plt
from pylab import *

pydb=pymysql.connect('localhost','root','19930625','world')
dbcursor=pydb.cursor()

sql="select population from country where continent=North America"

command=dbcursor.execute(sql,value)
data=dbcursor.fetchall()
Oceania=0
for row in data：
  for i in row:
    Oceania=Oceania+row[i]

import pymysql
import matplotlib.pyplot as plt
from pylab import *

pydb=pymysql.connect('localhost','root','19930625','world')
dbcursor=pydb.cursor()

sql="select population from country where continent=North America"

command=dbcursor.execute(sql,value)
data=dbcursor.fetchall()
Antarctica=0
for row in data：
  for i in row:
    Antarctica=Antarctica+row[i]


continentlist=['NorthAmerica','Asia','Africa','Europe','SouthAmerica','Oceania','Antarctica']
lifelist=[NorthAmerica,Asia,Africa,Europe,SouthAmerica,Oceania,Antarctica]

labels= continentlist
x=lifelist

explode=[]
for _ in range(len(labels)):
  explode.append(0.1)
pie(x,explode=explode,labels=labels,autopct='%1.1f%%',startangle=40)

title('population by continent')
show()

Q10

In [0]:
import matplotlib.pyplot as plt
import pandas as pd

filename = "energy-production.csv"
excel = pd.read_excel(filename, header=0)
year=input("please input a year between 1973 and 2014:")

yearlist=excel[year]
detail=('Solar/PV Energy',	'Geothermal Energy',	'Wind Energy'	,'Natural Gas Plant Liquids',	'Hydroelectric Power'	,'Biomass Energy','Nuclear Electric Power',	'Crude Oil'	,'Natural Gas (Dry)', 'Coal')

import matplotlib.pyplot as plt

x=('Bill','Fred','Mary','Sue')
money=[1.5,2.5,5.5,2.0]

plt.ylim(0,30)
plt.bar(yearlist,detail)
plt.show()
